server:
  port: 8702
  servlet:
    context-path: /auth
spring:
  application:
    name: auth-service
  kafka:
    bootstrap-servers: "kafka:9092"
  datasource:
    url: jdbc:postgresql://postgres:5432/unicrmdb
    username: postgres
    password: Qwe123
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: auth_schema
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        ddl-auto: none
        dialect: org.hibernate.dialect.PostgreSQLDialect
eureka:
  instance:
    hostname: auth-service
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://discovery:8700/eureka}
      fetchRegistry: false