server:
  port: 8702
  servlet:
    context-path: /auth
spring:
  application:
    name: auth-service
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=auth_schema
    username: postgres
    password: Qwe123
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        ddl-auto: none
        dialect: org.hibernate.dialect.PostgreSQLDialect
#  eureka:
#    instance:
#      hostname: localhost
#    client:
#      serviceUrl:
#        defaultZone: ${EUREKA_URI:http://eurika:8700/eureka}
#        fetchRegistry: false