server:
  port: 8705
  servlet:
    context-path: /analytic
spring:
  application:
    name: analytic-service
  kafka:
    bootstrap-servers: "kafka:9092"
    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring:
          deserializer:
            value:
              delegate:
                class: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: 2
  datasource:
    url: jdbc:postgresql://postgres:5432/unicrmdb
    username: postgres
    password: Qwe123
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: analytic_schema
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
eureka:
  instance:
    hostname: analytic-service
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://discovery:8700/eureka}
      fetchRegistry: false