version: '3'

services:
  postgres:
    image: postgres:9.6
    container_name: postgres_unicrm_container
    domainname: postgresUniCRM
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "unicrmdb"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "Qwe123"
    volumes:
      - ./postgres_init.sql:/docker-entrypoint-initdb.d/postgres_init.sql
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-U", "postgres" ]
      interval: 5s
      timeout: 1s
      retries: 2

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: Qwe123
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo
      ME_CONFIG_MONGODB_ADMINPASSWORD: Qwe123
      ME_CONFIG_MONGODB_URL: mongodb://mongo:Qwe123@mongo:27017/
    depends_on:
        - mongo