server:
  port: 8704
  servlet:
    context-path: /ticket
spring:
  application:
    name: ticket-service

  datasource:
    url: jdbc:postgresql://localhost:5432/unicrmdb?currentSchema=tickets_schema
    username: postgres
    password: Qwe123
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: db/changelog/db.changelog-master.xml
    enabled: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
#  eureka:
#    instance:
#      hostname: localhost
#    client:
#      serviceUrl:
#        defaultZone: ${EUREKA_URI:http://eurika:8700/eureka}
#        fetchRegistry: false
