server:
  port: 8704
  servlet:
    context-path: /ticket
spring:
  application:
    name: ticket-service
  datasource:
    url: jdbc:postgresql://postgres:5432/postgres
    username: postgres
    password: Qwe123
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8700/eureka}
      fetchRegistry: false